services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: build
    command: pnpm run start:dev
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - server/.env
    depends_on:
      - db
    environment:
      - NODE_ENV=development
  
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - NODE_ENV=development

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
