services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: build
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - server/.env
    depends_on:
      - db
  
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
